#include "io/StlWriter.h"

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <limits>

namespace spo {

namespace {

constexpr std::uintmax_t kHeaderSize = 80;

StlWriteResult write_error(const std::string& message) {
    StlWriteResult result;
    result.message = message;
    return result;
}

void write_bytes(std::ofstream& stream, const char* data, std::streamsize size) {
    stream.write(data, size);
}

void write_u16_le(std::ofstream& stream, std::uint16_t value) {
    const std::array<unsigned char, 2> bytes {
        static_cast<unsigned char>(value & 0xffu),
        static_cast<unsigned char>((value >> 8u) & 0xffu),
    };
    write_bytes(stream, reinterpret_cast<const char*>(bytes.data()), static_cast<std::streamsize>(bytes.size()));
}

void write_u32_le(std::ofstream& stream, std::uint32_t value) {
    const std::array<unsigned char, 4> bytes {
        static_cast<unsigned char>(value & 0xffu),
        static_cast<unsigned char>((value >> 8u) & 0xffu),
        static_cast<unsigned char>((value >> 16u) & 0xffu),
        static_cast<unsigned char>((value >> 24u) & 0xffu),
    };
    write_bytes(stream, reinterpret_cast<const char*>(bytes.data()), static_cast<std::streamsize>(bytes.size()));
}

void write_float_le(std::ofstream& stream, float value) {
    std::uint32_t bits = 0;
    static_assert(sizeof(bits) == sizeof(value));
    std::memcpy(&bits, &value, sizeof(bits));
    write_u32_le(stream, bits);
}

void write_vec3(std::ofstream& stream, const StlVec3& value) {
    write_float_le(stream, static_cast<float>(value.x));
    write_float_le(stream, static_cast<float>(value.y));
    write_float_le(stream, static_cast<float>(value.z));
}

void write_triangle(std::ofstream& stream, const StlTriangle& triangle) {
    write_vec3(stream, triangle.normal);
    write_vec3(stream, triangle.v0);
    write_vec3(stream, triangle.v1);
    write_vec3(stream, triangle.v2);
    write_u16_le(stream, 0);
}

}

StlWriteResult StlWriter::write(const StlMesh& mesh, const std::filesystem::path& path) const {
    if (mesh.empty()) {
        return write_error("Cannot write an empty STL mesh.");
    }

    if (mesh.triangleCount() > std::numeric_limits<std::uint32_t>::max()) {
        return write_error("STL mesh has too many triangles for binary STL.");
    }

    std::ofstream stream(path, std::ios::binary | std::ios::trunc);
    if (!stream) {
        return write_error("Could not open STL file for writing.");
    }

    std::array<char, kHeaderSize> header {};
    constexpr char kHeaderText[] = "Generated by STEP-PATCH-OPTIMIZER";
    std::copy_n(kHeaderText, std::min(sizeof(kHeaderText) - 1, header.size()), header.data());
    write_bytes(stream, header.data(), static_cast<std::streamsize>(header.size()));
    write_u32_le(stream, static_cast<std::uint32_t>(mesh.triangleCount()));

    for (const auto& triangle : mesh.triangles()) {
        write_triangle(stream, triangle);
    }

    if (!stream) {
        return write_error("Failed while writing STL file.");
    }

    StlWriteResult result;
    result.success = true;
    return result;
}

}
